version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project
prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data 4GB
    command: |
      . venv/bin/activate
      chmod +x ./scripts/fetch_kaggle_dataset.sh
      ./scripts/fetch_kaggle_dataset.sh

jobs:
  train_and_upload_neural_network_model:
    docker:
      - image: circleci/python:3.6.4-stretch
    working_directory: ~/project
    steps:
      - checkout
      - *prepare_venv
      - run: 
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r packages/neural_network_model/requirements.txt

      - *fetch_data
      - run:
          name: Train model 
          command: |
            . venv/bin/activate
            PYTHONPATH=./packages/
         