version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.7.0
  working_directory: ~/project
prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
fetch_data: &fetch_data
# TODO: Add kaggle script to download data for imageclef 2020
  run:
    name: Set script permissions and fetch data 4GB
    command: |
      . venv/bin/activate
      chmod +x ./scripts/fetch_kaggle_dataset_2020.sh
      ./scripts/fetch_kaggle_dataset_2020.sh

jobs:
  train_and_upload_cnn_modality_classifier:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - restore_cache:
          key: py-deps-{{ checksum "packages/cnn_modality_clf/requirements.txt"}}
      - run: 
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r packages/cnn_modality_clf/requirements.txt
      - save_cache:
          paths:
            - "/venv"
          key: py-deps-{{ checksum "packages/cnn_modality_clf/requirements.txt"}}

      - *fetch_data
      - run:
          name: Train model 
          command: |
            . venv/bin/activate

workflows:
  version: 2.1
  test-all:
    jobs:
      - train_and_upload_cnn_modality_classifier

         